import backgroundImg from "../../assets/imgs/IMG_8755.jpg";

export const styledHome = {
    logoBox: {
        background: `url(${backgroundImg}), rgb(150,150,150)`,
        backgroundRepeat: "no-repeat",
        backgroundSize: "cover",
        backgroundPosition: "50%",
        backgroundBlendMode: "multiply",
        height: "100vh",
        display: "flex",
        justifyContent: "space-around",
        marginBottom: "6vh",
    },
    pinkBackground: {
        backgroundColor: "#f7e8f0",
    },
    logoImg: {
        width: "60%",
        maxWidth: "498px",
        maxHeight: "392px",
        margin: "auto",
    },
    secundaryImg: { width: "50%", maxWidth: "300px", height: "auto" },
    homeBoxes: {
        width: "85%",
        maxWidth: "1000px",
        display: "flex",
        margin: "auto",
        justifyContent: "center",
        alignItems: "center",
    },
    homeBoxesRight: {
        width: "85%",
        maxWidth: "1000px",
        display: "flex",
        flexDirection: "row-reverse",
        margin: "-2em auto",
        padding: "9rem 0",
        justifyContent: "center",
        alignItems: "center",
    },
    textBoxes1: {
        display: "flex",
        flexDirection: "column",
        marginLeft: "-2rem",
        width: "70%",
    },
    textBoxes2: {
        display: "flex",
        flexDirection: "column",
        marginRight: "-2rem",
        width: "70%",
    },
    buttons: {
        margin: "-3.25em 25px 0 auto",
        borderRadius: "0px",
        backgroundColor: "#cd7fae",
        "&:hover": { backgroundColor: "#cd7fae" },
        boxShadow: "none",
        fontWeight: "200",
        padding: "1em",
        width: "33%",
        maxWidth: "100px",
        fontSize: "0.75rem",
    },
    buttons2: {
        margin: "-3.25em auto 0 25px",
        borderRadius: "0px",
        backgroundColor: "#cd7fae",
        "&:hover": { backgroundColor: "#cd7fae" },
        boxShadow: "none",
        fontWeight: "200",
        padding: "1em",
        width: "33%",
        maxWidth: "100px",
        fontSize: "0.75rem",
    },
    h2: {
        textTransform: "uppercase",
        color: "#cd7fae",
        fontWeight: "200",
        letterSpacing: "2px",
        fontSize: "1.125rem",
        padding: "1em 1.5em",
        margin: "0",
        backgroundColor: "#fff9f6",
        marginRight: "auto",
        marginLeft: "50px",
        alignItems: "flex-start",
        zIndex: "9",
    },
    p: {
        padding: "2rem 2.7rem",
        marginTop: "-2em",
        lineHeight: "2",
        fontSize: "0.85rem",
        backgroundColor: "#f7e8f0",
    },
    p2: {
        color: "#cd7fae",
        textAlign: "center",
        padding: "1.5em 0",
        lineHeight: "2",
        fontSize: "1.025rem",
        backgroundColor: "#fff9f6",
    },
};
